### PR TITLE
add different "anti-xss" methods for different purposes

### PR DESCRIPTION
**Pull request by voku**
- xss_clean_blank -> remove the full string, if XSS was found
- xss_clean_blacklist -> remove only the XSS part via blacklisting
- xss_clean_greylist -> remove only the XSS part via blacklisting, but try also to fix the dom
- xss_clean_whitelist -> re-build the full html and add only whitelisted stuff

---
This change is [Reviewable](https://reviewable.io/reviews/grahamcampbell/security-core/3)

### CODE REVIEW

**Comment by voku** [comment]
@GrahamCampbell what do you think about this?

**Comment by GrahamCampbell** [comment]
The only purpose of this package is to mimic the security class of code igniter. I'm not sure if we should go another route?

**Comment by GrahamCampbell** [comment]
Then again, I suppose that is quite outdated. What are the advantages of he new version compared to the original version? Are there any XSS cases that made it through before, but are now stopped?

**Comment by voku** [comment]
yep, I added many false-positive fixes and e.g. UTF7 encoding fixes

**Pull request closed without merging**
